import * as React from 'react';
import { Box, styled } from "@mui/material";
import { Breadcrumb, SimpleCard } from "app/components";
import AsyncAutocomplete from "./AsyncAutocomplete";
import AutocompleteCombo from "./AutocompleteCombo";
import BadgeAutocomplete from "./BadgeAutocomplete";
import Typography from '@mui/material/Typography';

import ControlledExpansionPanels from "./ControlledAccordion";

import { Card, Grid, useTheme } from "@mui/material";
import CardActionArea from '@mui/material/CardActionArea';
import CardMedia from '@mui/material/CardMedia';
import CardContent from '@mui/material/CardContent';



const Container = styled("div")(({ theme }) => ({
  margin: "30px",
  [theme.breakpoints.down("sm")]: { margin: "16px" },
  "& .breadcrumb": {
    marginBottom: "30px",
    [theme.breakpoints.down("sm")]: { marginBottom: "16px" }
  }
}));

export default function AppAutoComplete() {
  return (
    <Container>
      <Box className="breadcrumb">
        <Breadcrumb
          routeSegments={[{ name: "About Hearts and Minds" }]}
        />
      </Box>


      <Typography variant="h3" align="center" gutterBottom>
       About Hearts and Minds
      </Typography>

      <SimpleCard>
        <p>Hearts and Minds is a suite of tools – booklets, videos and other supporting materials – to help improve the safety culture of organisations.  The EI publishes the toolkit, provides access to training on how to use it, and has a network of independent consultants based globally who can help support your organisation’s cultural journey.</p>
        <p>The Energy Institute is also responsible for the continued development of the Hearts and Minds toolkit, through reinvesting the proceeds from sale of the toolkit into research and continuous development.</p>
        <p>The Energy Institute is a non-profit organisation.  Revenue generated by the sale of the Hearts and Minds toolkit is used to update and extend the toolkit by funding research and development, aimed at helping companies improve their HSE performance.</p>

        <ControlledExpansionPanels />

      </SimpleCard>

      <Box py="12px" />

      <SimpleCard title="Safety culture">

      <Grid container justifyContent="space-between" alignItems="center" marginTop={2} spacing={2} >

        <Grid size={3}>
        <Card sx={{ maxWidth: 250 }} style={{ marginTop: '20px' }} >
        <CardActionArea>
         <CardMedia
           sx={{ height: 140 }}
           image="/assets/images/learnmore.png"
           title="Learn more"
           style={{ width: '150px', height: '150px', marginLeft: '50px' }}
         />
         <CardContent>
           <Typography gutterBottom variant="h5" component="div">
             What is safety culture?
           </Typography>
           <Typography variant="body2" sx={{ color: 'text.secondary' }}>
             Lizards are a widespread group of squamate reptiles, with over 6,000
             species, ranging across all continents except Antarctica
           </Typography>
         </CardContent>
         </CardActionArea>
       </Card>
        </Grid>

        <Grid size={3}>
        <Card sx={{ maxWidth: 250 }} style={{ marginTop: '20px' }} >
        <CardActionArea>
         <CardMedia
           sx={{ height: 140 }}
           image="/assets/images/toolkit.png"
           title="Hearts and Minds Toolkit"
           style={{ height: '150px', width: '150px', marginLeft: '50px' }}
         />
         <CardContent>
           <Typography gutterBottom variant="h5" component="div">
             How to improve safety culture
           </Typography>
           <Typography variant="body2" sx={{ color: 'text.secondary' }}>
             Lizards are a widespread group of squamate reptiles, with over 6,000
             species, ranging across all continents except Antarctica
           </Typography>
         </CardContent>
         </CardActionArea>
       </Card>
        </Grid>



      </Grid>
      </SimpleCard>

      <Box py="12px" />


    </Container>
  );
}
